CREATE TABLE Funcionario (
    id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE Telefone (
    Telefone_PK INTEGER NOT NULL AUTO_INCREMENT,
    numero VARCHAR(255) NOT NULL,
    funcionarioId INTEGER NOT NULL,

    PRIMARY KEY (Telefone_PK)
);

CREATE TABLE Gerente (
    id INTEGER NOT NULL AUTO_INCREMENT,
    funcionarioId INTEGER NOT NULL,

    UNIQUE INDEX Gerente_funcionarioId_key(funcionarioId),
    PRIMARY KEY (id)
);

CREATE TABLE Camareira (
    id INTEGER NOT NULL AUTO_INCREMENT,
    funcionarioId INTEGER NOT NULL,
    gerenteId INTEGER NOT NULL,

    UNIQUE INDEX Camareira_funcionarioId_key(funcionarioId),
    PRIMARY KEY (id)
);

CREATE TABLE Cliente (
    id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    RG VARCHAR(255) NOT NULL,

    UNIQUE INDEX Cliente_CPF_key(CPF),
    PRIMARY KEY (id)
);

CREATE TABLE Servico (
    id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    valor DOUBLE NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE Produto (
    id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    valor DOUBLE NOT NULL,
    custo DOUBLE NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE Quarto (
    id INTEGER NOT NULL AUTO_INCREMENT,
    numero INTEGER NOT NULL,
    tipo ENUM("DELUXE", "SUITE") DEFAULT "SUITE" NOT NULL,
    status ENUM("DISPONIVEL", "MANUTENCAO", "LIMPEZA") DEFAULT "DISPONIVEL" NOT NULL,
    valor FLOAT NOT NULL,

    PRIMARY KEY (id)
);

-- Quarto Possui tantos Produtos.
CREATE TABLE Possui (
    produtoId INTEGER NOT NULL,
    quartoId INTEGER NOT NULL,
    quantidade INTEGER,

    PRIMARY KEY (produtoId, quartoId)
);

CREATE TABLE Reserva (
	id INTEGER NOT NULL AUTO_INCREMENT,
	status ENUM("CONFIRMADA", "CANCELADA", "FINALIZADA") DEFAULT "CONFIRMADA" NOT NULL,
	data_checkin DATETIME DEFAULT (CURRENT_TIMESTAMP),
	data_checkout DATETIME NULL,
	funcionarioId INTEGER NOT NULL,
	clienteId INTEGER NOT NULL,
	quartoId INTEGER NOT NULL,
	
	PRIMARY KEY (id)
);

CREATE TABLE Consumo (
	id INTEGER NOT NULL AUTO_INCREMENT,
	produtoId INTEGER,
	servicoId INTEGER,
	clienteId INTEGER NOT NULL,
	data_consumo DATETIME DEFAULT (CURRENT_TIMESTAMP),
	quantidade INTEGER,
	valor FLOAT,
	
	PRIMARY KEY (id)
);

CREATE TABLE Pagamento (
	id INTEGER NOT NULL AUTO_INCREMENT,
	clienteId INTEGER NOT NULL,
	reservaId INTEGER,
	consumoId INTEGER,
	payment_provider_id BIGINT NOT NULL,
	forma_pagamento ENUM("PIX", "CREDITO", "DEBITO", "DINHEIRO") DEFAULT "PIX" NOT NULL,
	
	PRIMARY KEY (id)
);



ALTER TABLE Telefone ADD CONSTRAINT Telefone_funcionarioId_fkey FOREIGN KEY (funcionarioId) REFERENCES Funcionario(id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Gerente ADD CONSTRAINT Gerente_funcionarioId_fkey FOREIGN KEY (funcionarioId) REFERENCES Funcionario(id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Camareira ADD CONSTRAINT Camareira_funcionarioId_fkey FOREIGN KEY (funcionarioId) REFERENCES Funcionario(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Camareira ADD CONSTRAINT Camareira_gerenteId_fkey FOREIGN KEY (gerenteId) REFERENCES Gerente(id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Possui ADD CONSTRAINT Possui_produtoId_fkey FOREIGN KEY (produtoId) REFERENCES Produto(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Possui ADD CONSTRAINT Possui_quartoId_fkey FOREIGN KEY (quartoId) REFERENCES Quarto(id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Reserva ADD CONSTRAINT Reserva_funcionarioId_fkey FOREIGN KEY (funcionarioId) REFERENCES Funcionario(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Reserva ADD CONSTRAINT Reserva_clienteId_fkey FOREIGN KEY (clienteId) REFERENCES Cliente(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Reserva ADD CONSTRAINT Reserva_quartoId_fkey FOREIGN KEY (quartoId) REFERENCES Quarto(id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Consumo ADD CONSTRAINT Consumo_produtoId_fkey FOREIGN KEY (produtoId) REFERENCES Produto(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Consumo ADD CONSTRAINT Consumo_servicoId_fkey FOREIGN KEY (servicoId) REFERENCES Servico(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Consumo ADD CONSTRAINT Consumo_clienteId_fkey FOREIGN KEY (clienteId) REFERENCES Cliente(id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Pagamento ADD CONSTRAINT Pagamento_clienteId_fkey FOREIGN KEY (clienteId) REFERENCES Cliente(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Pagamento ADD CONSTRAINT Pagamento_reservaId_fkey FOREIGN KEY (reservaId) REFERENCES Reserva(id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Pagamento ADD CONSTRAINT Pagamento_consumoId_fkey FOREIGN KEY (consumoId) REFERENCES Consumo(id) ON DELETE RESTRICT ON UPDATE CASCADE;
